/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Administrador;
import Clases.Nivel;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import proyectooop.ProyectoOOP;
import static proyectooop.ProyectoOOP.programa;

/**
 *
 * @author Josua
 */
public class hacerNivel extends javax.swing.JFrame {

    /**
     * Creates new form hacerNivel
     */
    
    public Nivel level;
    public int cajas=0;
    public int puntos=0;
    public int[][] matriz;
    public Administrador adm;
    
    public hacerNivel() {
        initComponents();
        
        this.getContentPane().setBackground(new Color(200,200,255));    //color a la ventana
        this.setLocationRelativeTo(null);   //centrar pantalla       
        men.setForeground(Color.red);
        men1.setForeground(Color.red);
        exit.setForeground(Color.blue);
        
        
        exi.setVisible(false);
        ge.setVisible(true);
        exi.setForeground(Color.green);
        ge.setForeground(Color.blue);
        perso.setForeground(Color.blue);
        caja.setForeground(Color.blue);
        punto.setForeground(Color.blue);
        pared.setForeground(Color.blue);
        asigna.setForeground(Color.blue);
        as.setForeground(Color.blue);
        terminar.setForeground(Color.blue);
        men.setVisible(false);
        men1.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        perso = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        caja = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        punto = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pared = new javax.swing.JButton();
        ge = new javax.swing.JButton();
        terminar = new javax.swing.JButton();
        men = new javax.swing.JLabel();
        men1 = new javax.swing.JLabel();
        col = new javax.swing.JTextField();
        fil = new javax.swing.JTextField();
        col1 = new javax.swing.JTextField();
        fil1 = new javax.swing.JTextField();
        col2 = new javax.swing.JTextField();
        fil2 = new javax.swing.JTextField();
        col3 = new javax.swing.JTextField();
        fil3 = new javax.swing.JTextField();
        col4 = new javax.swing.JTextField();
        fil4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        moves = new javax.swing.JTextField();
        asigna = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        nume = new javax.swing.JTextField();
        as = new javax.swing.JButton();
        exi = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Haciendo un nivel");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel1.setText("Numero de Columnas");

        jLabel2.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel2.setText("Numero de filas");

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setText("Generación de la matriz");

        jLabel4.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel4.setText("Ubicar personaje");

        jLabel5.setText("->");

        jLabel6.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel6.setText("Columna");

        jLabel7.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel7.setText("Fila");

        perso.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        perso.setText("Ubicar");
        perso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel8.setText("Hacer caja");

        jLabel9.setText("->");

        jLabel10.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel10.setText("Columna");

        jLabel11.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel11.setText("Fila");

        caja.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        caja.setText("Hacer");
        caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel12.setText("Hacer punto");

        jLabel13.setText("->");

        jLabel14.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel14.setText("Columna");

        jLabel15.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel15.setText("Fila");

        punto.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        punto.setText("Hacer");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel16.setText("Hacer pared");

        jLabel17.setText("->");

        jLabel18.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel18.setText("Columna");

        jLabel19.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel19.setText("Fila");

        pared.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        pared.setText("Hacer");
        pared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paredActionPerformed(evt);
            }
        });

        ge.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        ge.setText("Generar matriz");
        ge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geActionPerformed(evt);
            }
        });

        terminar.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        terminar.setText("Terminar y agregar nivel");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        men.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        men.setText("Ocurrió un error en el ingreso de datos");

        men1.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        men1.setText("Procure que exista la misma cantidad de cajas y de puntos");

        jLabel20.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel20.setText("Best Moves");

        asigna.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        asigna.setText("Asignar");
        asigna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        jLabel21.setText("Numero de nivel");

        as.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        as.setText("Asignar");
        as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asActionPerformed(evt);
            }
        });

        exi.setFont(new java.awt.Font("Stencilia-Bold", 0, 11)); // NOI18N
        exi.setText("Proceso terminado con exito");

        exit.setFont(new java.awt.Font("Stencil Std", 0, 11)); // NOI18N
        exit.setText("Volver");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/fondoNivel.fw.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(ge))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(fil1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(perso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(col2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(fil2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(col3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(fil3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel17)
                        .addGap(119, 119, 119)
                        .addComponent(col4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(asigna, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nume, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(exi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(men, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(men1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(caja, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(as))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(moves, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(fil4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(col1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(pared, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(fil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ge)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(fil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(perso)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(col2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(col3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(col4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asigna)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(terminar)
                .addGap(18, 18, 18)
                .addComponent(exi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(men, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(men1)))
                .addGap(6, 6, 6)
                .addComponent(exit))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(caja))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel20))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(as))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel15))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(moves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(fil4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(col1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel19))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(pared))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(fil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel18))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel13))
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geActionPerformed
        // TODO add your handling code here:
        
        if ((esnumero(col.getText())==true)&&(esnumero(fil.getText())==true)){
        
        if (!col.getText().equals("")&&(!fil.getText().equals(""))){
            
            men.setVisible(false);
            // se inicializa el nivel con el tamaño
            level=new Nivel (Integer.parseInt(col.getText()),Integer.parseInt(fil.getText()));
            
            //se asigna la matriz
            matriz=new int [Integer.parseInt(fil.getText())][Integer.parseInt(col.getText())];
            col.setEditable(false);
            fil.setEditable(false);
            
            //ge.;
            
            //se coloca ceros de la matriz
            
            int colu=level.getColumnas();
            int c=0;
            int var=0;
            while(var<colu){
                
               matriz[c][var]=0;
               var++;
            }
            
            
            
            
            int cont=0;
            int conta=level.getColumnas()-2;
            int iterador=1;
            
            while(iterador<level.getFilas()-1){
                matriz[iterador][cont]=0;       //se colocan los ceros
                matriz[iterador][conta]=0;
                iterador++;
                
            }
            
            cont=level.getFilas()-1;
            conta=1;
            while(conta<level.getColumnas()-1){
                
                matriz[cont][conta]=0;
                conta++;
            }
            
            
            cont=1;
            conta=1;            //colocando espacios en la matriz grafica
           
            while(conta<level.getFilas()-1){
                cont=1;
            while(cont<level.getColumnas()-1){
                matriz[conta][cont]=4;
                cont++;
            }
            conta++;
            }
            
            level.generarMatriz();
            level.setMatrizLogica(matriz);  //se asigna la matriz a la matriz manejada por el nivel
            
        }
        
        else{
        
            men.setVisible(true);
        }}
        
        else{ men.setVisible(true);}
    }//GEN-LAST:event_geActionPerformed

    private void persoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persoActionPerformed
        // TODO add your handling code here:
        
        
        
        if ((esnumero(col1.getText())==true)&&(esnumero(fil1.getText())==true)){
              int x=Integer.parseInt(col1.getText());
            int y=Integer.parseInt(fil1.getText());
            
            if( (x>0)&&(x<level.getColumnas()-1)&&((y>0)&&(y<level.getFilas()-1))){
            
            
            level.ubicarPersonaje(x,y);
            col1.setEditable(false);    //se guardan datos del personaje
            fil1.setEditable(false);
            men.setVisible(false);
            level.setPersonajeColumna(x);
            level.setPersonajeFila(y);
            
            }
            
            else{
                men.setVisible(true);}
        }
        
        else{
        
            men.setVisible(true);
        }
        
    }//GEN-LAST:event_persoActionPerformed

    private void cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaActionPerformed
        // TODO add your handling code here:
        
        if ((esnumero(col2.getText())==true)&&(esnumero(fil2.getText())==true)){
            
            int x=Integer.parseInt(col2.getText());
            int y=Integer.parseInt(fil2.getText());
            
            //validacion de que la caja no se inserte en extremos de la matriz ya que estos siempre son paredes
            
            if( (x>0)&&(x<level.getColumnas()-1)&&((y>0)&&(y<level.getFilas()-1))){
            men.setVisible(false);
            level.hacerCaja(x,y);
            cajas++; // se aumenta el contador de cajas
            col2.setText("");
            fil2.setText("");
            
            }
            
            else{men.setVisible(true); }
            
        }
        
        else{
        
            men.setVisible(true);
        }
        
    }//GEN-LAST:event_cajaActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
         
        if ((esnumero(col3.getText())==true)&&(esnumero(fil3.getText())==true)){
            
            int x=Integer.parseInt(col3.getText());
            int y=Integer.parseInt(fil3.getText());
            
            if( (x>0)&&(x<level.getColumnas()-1)&&((y>0)&&(y<level.getFilas()-1))){
            men.setVisible(false);
            level.hacerPunto(Integer.parseInt(col3.getText()), Integer.parseInt(fil3.getText()));
            puntos++;
            
            col3.setText("");
            fil3.setText("");
            
            }
            
            else{men.setVisible(true); }
            
        }
        
        else{
        
            men.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_puntoActionPerformed

    private void paredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paredActionPerformed
        // TODO add your handling code here:
         if ((esnumero(col4.getText())==true)&&(esnumero(fil4.getText())==true)){
            
            int x=Integer.parseInt(col4.getText());
            int y=Integer.parseInt(fil4.getText());
            
            //lo mismo que con cajas
            
            if( (x>0)&&(x<level.getColumnas()-1)&&((y>0)&&(y<level.getFilas()-1))){
            men.setVisible(false);
            level.hacerPared(Integer.parseInt(col4.getText()), Integer.parseInt(fil4.getText()));
            
            col4.setText("");
            fil4.setText("");
            
            }
            
            else{men.setVisible(true); }
            
        }
        
        else{
        
            men.setVisible(true);
        }
        
        
    }//GEN-LAST:event_paredActionPerformed

    private void asignaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignaActionPerformed
        // TODO add your handling code here:
        
        if (esnumero(moves.getText())==true){
        
            // movimientos necesarios para resolver el nivel
            level.setBestMoves(Integer.parseInt(moves.getText()));  
            
            }
        else{men.setVisible(true); }
        
    }//GEN-LAST:event_asignaActionPerformed

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        // TODO add your handling code here:
        
        int result= level.validarMatriz();
        if (result!=2){
            
            men.setVisible(false);
            adm=(Administrador) ProyectoOOP.usuario;
            level.setCedulaAdministrador(adm.getCedula());      //para saber quien hizo el nivel;
            level.setNombreAdministrador(adm.getNombre());
            level.setCantCajas(cajas);
            level.setCantPuntos(puntos);    //para saber la cantidad de cajas y de puntos del nivel
            exi.setVisible(true);
            programa.agregarNivel(level);  //se agrega el nivel a la lista general de niveles
            
        
        }
        
        else{
        
            men1.setVisible(true);
            
        }
        
    }//GEN-LAST:event_terminarActionPerformed

    private void asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asActionPerformed
        // TODO add your handling code here:
        
        if (esnumero(moves.getText())==true){
            
            men.setVisible(false);
            level.setNumNivel(Integer.parseInt(moves.getText()));   //se agrega el numero de nivel
            
            }
        else {men.setVisible(true); }
        
    }//GEN-LAST:event_asActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new ventanaAdministrador().setVisible(true);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(hacerNivel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(hacerNivel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(hacerNivel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_exitActionPerformed

      public boolean esnumero(String texto){
    
	try {
		Integer.parseInt(texto);
		return true;
	} catch (NumberFormatException mistake){    //si no todos los caracteres son numeros
		return false;
    
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hacerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hacerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hacerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hacerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hacerNivel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton as;
    private javax.swing.JButton asigna;
    private javax.swing.JButton caja;
    private javax.swing.JTextField col;
    private javax.swing.JTextField col1;
    private javax.swing.JTextField col2;
    private javax.swing.JTextField col3;
    private javax.swing.JTextField col4;
    private javax.swing.JLabel exi;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fil;
    private javax.swing.JTextField fil1;
    private javax.swing.JTextField fil2;
    private javax.swing.JTextField fil3;
    private javax.swing.JTextField fil4;
    private javax.swing.JButton ge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel men;
    private javax.swing.JLabel men1;
    private javax.swing.JTextField moves;
    private javax.swing.JTextField nume;
    private javax.swing.JButton pared;
    private javax.swing.JButton perso;
    private javax.swing.JButton punto;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables
}
