/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import Clases.*;
import java.util.ArrayList;
import proyectooop.ProyectoOOP;
import ventanas.*;
import static proyectooop.ProyectoOOP.programa;


/**
 *
 * @author Josua
 */
public class inicioSesion extends javax.swing.JFrame {
    
 
    
    //Programa nuevo=programa;
   
    /**
     * Creates new form inicioSesion
     */
    public inicioSesion() {
        initComponents();
        this.getContentPane().setBackground(new Color(200,200,255));    //color a la ventana
        //ingresar.setBackground(Color.yellow);           //color de fondo al boton
        ingresar.setForeground(Color.blue);             //color de la letra del boton
        registraAdmin.setForeground(Color.blue);
        registrarJugador.setForeground(Color.blue);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contraseña = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        registraAdmin = new javax.swing.JButton();
        registrarJugador = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla de acceso");
        setResizable(false);

        contraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contraseña.setText("Contraseña");

        nombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombreUsuario.setText(" Nombre de Usuario");

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        registraAdmin.setText("Registrarse como administrador");
        registraAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraAdminActionPerformed(evt);
            }
        });

        registrarJugador.setText("Registrarse como Jugador");
        registrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(registraAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(registrarJugador)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(ingresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombreUsuario)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(contraseña))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ingresar)
                .addGap(18, 18, 18)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraAdmin)
                    .addComponent(registrarJugador))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registraAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraAdminActionPerformed
        // TODO add your handling code here:
        this.dispose(); //se esconde la ventana
        new RegistrarAdministrador().setVisible(true);
        mensaje.setText("");
    }//GEN-LAST:event_registraAdminActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
       
        String nombre=usuario.getText();   //se obtiene el nombre digitado
        String contra="";
        char [] code=password.getPassword();    //el password field encripta lo que se digita debe 
                                                //usarse el getpassword y no el gettext(), y pasar la cadena de
                                                //caracteres al string
       
        password.setText("");
        usuario.setText("");
        for (int i=0;i<code.length;i++){
        
            contra+=code[i];
        }
       
           
        boolean esta;
        esta=programa.login(nombre, contra);
        
       
         
        if (esta==true){
            
            //mensaje.setText("Si estas");        //si esta
            
            
            for (int i=0;i<programa.users.size();i++){
            
                if ((programa.users.get(i).getContraseña().equals(contra))&&(programa.users.get(i).getNombre().equals(nombre))){
                    ProyectoOOP.usuario= programa.users.get(i);
                    break;          //se termina el ciclo
                            
                }
            }
            
            if ( ProyectoOOP.usuario instanceof Administrador){  // si es instancia de administrador
                        
                    
                    new ventanaAdministrador().setVisible(true);
                    this.dispose();
                }
                
            else{  
                   new ventanaJugador().setVisible(true);
                   this.dispose();
            }
         
            contra="";
        }
        else{
          
            mensaje.setForeground(Color.red);
            mensaje.setText("Alguno de los datos es incorrecto");
            contra="";
        }
        
        
    }//GEN-LAST:event_ingresarActionPerformed

    private void registrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarJugadorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RegistrarJugador().setVisible(true);
        mensaje.setText("");
    }//GEN-LAST:event_registrarJugadorActionPerformed
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registraAdmin;
    private javax.swing.JButton registrarJugador;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
