/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import Clases.*;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import proyectooop.ProyectoOOP;
import ventanas.*;
import static proyectooop.ProyectoOOP.programa;


/**
 *
 * @author Josua
 */
public class inicioSesion extends javax.swing.JFrame {

    private static Clip clip;
    
 
    
    //Programa nuevo=programa;
   
    /**
     * Creates new form inicioSesion
     */
    public inicioSesion() throws IOException, UnsupportedAudioFileException, LineUnavailableException {
        initComponents();
        this.getContentPane().setBackground(new Color(200,200,255));    //color a la ventana
        this.setLocationRelativeTo(null);   //centrar pantalla
        ingresar.setForeground(Color.blue);             //color de la letra del boton
        registraAdmin.setForeground(Color.blue);
        registrarJugador.setForeground(Color.blue);
        Musica("Fortree_City.wav");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contraseña = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        registraAdmin = new javax.swing.JButton();
        registrarJugador = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla de acceso");
        setResizable(false);

        contraseña.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        contraseña.setText("Contraseña");

        nombreUsuario.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        nombreUsuario.setText(" Nombre de Usuario");

        ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/BotonIngresar.fw.png"))); // NOI18N
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        registraAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/BotonAdmin.fw.png"))); // NOI18N
        registraAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraAdminActionPerformed(evt);
            }
        });

        registrarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/BotonJugador.fw.png"))); // NOI18N
        registrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarJugadorActionPerformed(evt);
            }
        });

        mensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/menuprincipal.fw.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(registraAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(registrarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(registraAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(registrarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registraAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraAdminActionPerformed
        // TODO add your handling code here:
        this.dispose(); //se esconde la ventana
        new RegistrarAdministrador().setVisible(true);
        mensaje.setText("");
        usuario.setText("");
        password.setText("");
        
    }//GEN-LAST:event_registraAdminActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
       
        String nombre=usuario.getText();   //se obtiene el nombre digitado
        String contra="";
        char [] code=password.getPassword();    //el password field encripta lo que se digita debe 
                                                //usarse el getpassword y no el gettext(), y pasar la cadena de
                                                //caracteres al string
       
        password.setText("");
        usuario.setText("");
        for (int i=0;i<code.length;i++){
        
            contra+=code[i];
        }
       
           
        boolean esta;
        esta=programa.login(nombre, contra);
        
       
         
        if (esta==true){
            
            mensaje.setText("");        //si esta
            
            
            for (int i=0;i<programa.users.size();i++){
            
                if ((programa.users.get(i).getContraseña().equals(contra))&&(programa.users.get(i).getNombre().equals(nombre))){
                    ProyectoOOP.usuario= programa.users.get(i);
                    break;          //se termina el ciclo
                            
                }
            }
            
            if ( ProyectoOOP.usuario instanceof Administrador){  // si es instancia de administrador
                        
                    clip.stop();
                try {
                    new ventanaAdministrador().setVisible(true);
                } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
                    Logger.getLogger(inicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
                    this.dispose();
                }
                
            else{  
                    clip.stop();
                try {
                    new ventanaJugador().setVisible(true);
                } catch (IOException | UnsupportedAudioFileException | LineUnavailableException ex) {
                    Logger.getLogger(inicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
                   this.dispose();
            }
         
            contra="";
        }
        else{
            Font fuente = new Font("Stencilia-Bold", 1, 20);
            mensaje.setForeground(Color.red);
            mensaje.setFont(fuente);
            mensaje.setText("Alguno de los datos es incorrecto");
            contra = "";
        }
        
        
    }//GEN-LAST:event_ingresarActionPerformed

    private void registrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarJugadorActionPerformed

        this.dispose();
        new RegistrarJugador().setVisible(true);
        mensaje.setText("");
        usuario.setText("");
        password.setText("");
        
    }//GEN-LAST:event_registrarJugadorActionPerformed
    
   public static void Musica(String soundFile) throws LineUnavailableException, IOException, UnsupportedAudioFileException {
    File f = new File("./" + soundFile);
    AudioInputStream audioIn = AudioSystem.getAudioInputStream(f.toURI().toURL());  
    clip = AudioSystem.getClip();
    clip.open(audioIn);
    clip.loop(Clip.LOOP_CONTINUOUSLY);
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new inicioSesion().setVisible(true);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(inicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(inicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(inicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registraAdmin;
    private javax.swing.JButton registrarJugador;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
