/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Grupo;
import Clases.Jugador;
import Clases.Nivel;
import Clases.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import proyectooop.ProyectoOOP;
import static proyectooop.ProyectoOOP.programa;


public class juegoGrupal extends javax.swing.JFrame {

    public Jugador jugador;
    public Nivel level;
    private int maximoJug = 1;
    private int maximoNiveles = 0;
    public Grupo group=new Grupo();
    
    ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<Nivel> nivelesGrupo = new ArrayList();
    
    public juegoGrupal() {
        initComponents();
        this.setLocationRelativeTo(null);
        niv.setForeground(Color.red);
        jug.setForeground(Color.red);
        datos.setForeground(Color.red);
        maxJuga.setForeground(Color.red);
        maxlevels.setForeground(Color.red);
        niv.setVisible(false);
        jug.setVisible(false);
        datos.setVisible(false);
        maxJuga.setVisible(false);
        maxlevels.setVisible(false);
        jugador=(Jugador)ProyectoOOP.usuario;
        jugadores.add (jugador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cedu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nivel = new javax.swing.JTextField();
        Jugar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jug = new javax.swing.JLabel();
        niv = new javax.swing.JLabel();
        datos = new javax.swing.JLabel();
        addJugador = new javax.swing.JButton();
        addNivel = new javax.swing.JButton();
        maxJuga = new javax.swing.JLabel();
        maxlevels = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Creación de Juegos Grupales");

        jLabel2.setText("Ingrese el número de cedula del jugador que desea agregar al grupo (máximo 4 jugadores).");

        jLabel3.setText("Cedula:");

        jLabel6.setText("Ingrese un nivel que desea jugar (máximo 5 niveles)");

        jLabel7.setText("Número de Nivel:");

        Jugar.setText("Jugar!");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jug.setText("Este Jugador no existe");

        niv.setText("Este Nivel no existe");

        datos.setText("Ingrese al menos un nivel y un jugador, por favor");

        addJugador.setText("Añadir Jugador");
        addJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJugadorActionPerformed(evt);
            }
        });

        addNivel.setText("Añadir Nivel");
        addNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNivelActionPerformed(evt);
            }
        });

        maxJuga.setText("Ya ingresó el máximo de Jugadores.");

        maxlevels.setText("Ya ingresó el máximo de Niveles.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Salir)
                        .addGap(31, 31, 31)
                        .addComponent(Jugar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addJugador)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cedu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(maxJuga)
                                .addComponent(jug)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(142, 142, 142)
                                    .addComponent(addNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(niv)
                                .addComponent(maxlevels)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxJuga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addJugador)
                    .addComponent(jug))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxlevels))
                .addGap(4, 4, 4)
                .addComponent(niv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNivel)
                .addGap(50, 50, 50)
                .addComponent(datos)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(Jugar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
        new ventanaJugador().setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        
       if ((maximoJug >= 2)&&(nivelesGrupo != null)){
           //se llama la función de jugar con los datos de los jugadores y niveles agregados por el usuario
           
           
           group.setJugadores(jugadores);   //se agregan los jugadores al objeto grupo
           group.setNiveles(nivelesGrupo);  //se agregan niveles
           group.setGenerador(proyectooop.ProyectoOOP.usuario.getNombre()); //nombre del jugador que generó el grupo
           
           programa.agregaraGrupoLista(group);  //se agrega el grupo recien hecho a la lista de programa
           System.out.print("A Juegar!!!");
       }
       else
           datos.setVisible(true);        
    }//GEN-LAST:event_JugarActionPerformed

    private void addJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJugadorActionPerformed
        if (maximoJug < 4){
        
        if ((cedu.getText().length()==9)&&(esnumero(cedu.getText())==true)){
            Usuario use=programa.buscarUsuario(Integer.parseInt(cedu.getText()));
            if (use != null){
                jugador=(Jugador) use;
                jugadores.add(jugador);
                maximoJug ++;
                cedu.setText("");
                
            }
            else
                jug.setVisible(true);
                cedu.setText("");

            }
        }
        else
            maxJuga.setVisible(true);
            cedu.setText("");
    }//GEN-LAST:event_addJugadorActionPerformed

    private void addNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNivelActionPerformed
        if (maximoNiveles < 5){
        
        if (esnumero(nivel.getText())==true){
            Nivel use=programa.buscarNivel(Integer.parseInt(nivel.getText()));
            if (use != null){
                level=(Nivel) use;
                nivelesGrupo.add(level);
                maximoNiveles ++;
                nivel.setText("");
            }
            else
                niv.setVisible(true);
                nivel.setText("");
            }
        }
        else
            maxlevels.setVisible(true);
            nivel.setText("");
    }//GEN-LAST:event_addNivelActionPerformed

    public boolean esnumero(String texto){
    
	try {
		Integer.parseInt(texto);
		return true;
	} catch (NumberFormatException mistake){    //si no todos los caracteres son numeros
		return false;
    
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juegoGrupal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juegoGrupal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juegoGrupal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juegoGrupal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juegoGrupal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton addJugador;
    private javax.swing.JButton addNivel;
    private javax.swing.JTextField cedu;
    private javax.swing.JLabel datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel jug;
    private javax.swing.JLabel maxJuga;
    private javax.swing.JLabel maxlevels;
    private javax.swing.JLabel niv;
    private javax.swing.JTextField nivel;
    // End of variables declaration//GEN-END:variables
}
