/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Jugador;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyectooop.*;
import static proyectooop.ProyectoOOP.programa;
/**
 *
 * @author Josua
 */
public class RegistrarJugador extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarJugador
     */
    
    // para el formato de la imagen
    private FileNameExtensionFilter archivo= new FileNameExtensionFilter("Archivo de imagen","png");
    String direccionImagen;
    
    public RegistrarJugador() {
        initComponents();
        this.getContentPane().setBackground(new Color(200,250,200));    //color a la ventana
        this.setLocationRelativeTo(null);   //centrar pantalla
        registro.setForeground(Color.blue);
        volver.setForeground(Color.blue);
        adv.setForeground(Color.red);
        direccionImagen="";
        Calendar Cal= Calendar.getInstance(); 
        String fec= Cal.get(Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+"/"+Cal.get(Cal.YEAR);
        fecha.setText(fec);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registro = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        exito = new javax.swing.JLabel();
        adv = new javax.swing.JLabel();
        id = new javax.swing.JFormattedTextField();
        mostrar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Jugador");
        setPreferredSize(new java.awt.Dimension(551, 475));
        setResizable(false);
        setSize(new java.awt.Dimension(559, 496));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Jugador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 230, 39);

        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/BotonRegistar.fw.png"))); // NOI18N
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro);
        registro.setBounds(210, 350, 110, 37);

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/BotonRegresar.fw.png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(210, 410, 110, 38);

        jLabel2.setFont(new java.awt.Font("Stencilia-A", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 77, 24);
        getContentPane().add(nom);
        nom.setBounds(170, 70, 166, 24);

        jLabel3.setFont(new java.awt.Font("Stencilia-Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 105, 25);

        jLabel4.setFont(new java.awt.Font("Stencilia-Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 80, 27);
        getContentPane().add(correos);
        correos.setBounds(170, 150, 166, 27);

        jLabel5.setFont(new java.awt.Font("Stencilia-Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de Registro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 190, 147, 29);

        jLabel6.setFont(new java.awt.Font("Stencilia-Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 120, 31);
        getContentPane().add(password);
        password.setBounds(170, 230, 166, 30);
        getContentPane().add(exito);
        exito.setBounds(20, 340, 200, 20);

        adv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(adv);
        adv.setBounds(20, 320, 307, 23);

        try {
            id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        id.setToolTipText("9 dígitos, incluya ceros");
        getContentPane().add(id);
        id.setBounds(170, 110, 166, 25);
        getContentPane().add(mostrar);
        mostrar.setBounds(346, 59, 182, 196);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/BotonImagen.fw.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(376, 280, 116, 40);

        fecha.setEditable(false);
        fecha.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(fecha);
        fecha.setBounds(170, 194, 166, 27);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUsuario/menuregistrar.fw.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(560, 510));
        jLabel8.setMinimumSize(new java.awt.Dimension(560, 510));
        jLabel8.setPreferredSize(new java.awt.Dimension(560, 510));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 570, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.dispose(); //se cierra la ventana
        ProyectoOOP.ventana.setVisible(true);
        
    }//GEN-LAST:event_volverActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
        
            
    String nombre;
    String contra="";
    String correo;
    String cedula;
    
    String fechaRegistro;
    
    nombre=nom.getText();
    char [] cadena =password.getPassword();
    for (int i=0;i<cadena.length;i++){
        contra+=cadena[i];
    }
    
    correo=correos.getText();
    cedula=(id.getText());
    
    fechaRegistro=fecha.getText();
                                    //se valida que no hayan datos incorrectos
    if ((!nombre.equals(""))&&(cedula.length()==9)&&(!contra.equals(""))&&(!correo.equals(""))&&(!fechaRegistro.equals(""))){
    
        adv.setText("");
        int numero= Integer.parseInt(cedula);
        Jugador nuevo = new Jugador (nombre,numero,correo,contra,fechaRegistro);
        nuevo.setFotografia(direccionImagen); //variable que guardó la direccion de la imagen seleccionada
        programa.agregarUsuario(nuevo);   //se agrega
        Font fuente = new Font("Stencilia-Bold", 1, 20);
        exito.setFont(fuente);
        exito.setForeground(Color.green);
        exito.setText("Registro exitoso");
        
        nom.setText("");
        password.setText("");
        correos.setText("");
        id.setText("");
      
        fecha.setText("");
        mostrar.setIcon(new ImageIcon(""));
        direccionImagen="";
    }
    
    else{  
        Font fuente = new Font("Stencilia-Bold", 1, 20);
        adv.setFont(fuente);
        adv.setText("Existen apartados en blanco");}
    }//GEN-LAST:event_registroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //se hace un objeto tipo Jfilechooser
        
        JFileChooser nuevo = new JFileChooser ();
        
        // se establece el formato de la imagen a aceptar
        nuevo.setFileFilter(archivo);
        
        //abrir la ventana de dialogo en esta ventana para selleccionar imagen
        int var =nuevo.showOpenDialog(this);
        
        if (var==JFileChooser.APPROVE_OPTION){   // si selecciono una imagen
                    //obtener el archivo seleeccionado
               String seleccionado= nuevo.getSelectedFile().getPath();
                
                   // obtener direccion donde se guardara la imagen
               String direccion= nuevo.getSelectedFile().toString();
               mostrar.setIcon(new ImageIcon(seleccionado));
               
               ImageIcon imagen = new ImageIcon(seleccionado);
               
               Image photo = imagen.getImage();
               
               //cambiar tamaño a la imagen
               Image nueva= photo.getScaledInstance(155, 175, java.awt.Image.SCALE_SMOOTH);
               
               //generando imageicon con la nueva imagen
               
               ImageIcon icono= new ImageIcon(nueva);
               mostrar.setIcon(icono);
               mostrar.setSize(155, 175);
               
               direccionImagen=seleccionado;
    }//GEN-LAST:event_jButton1ActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adv;
    private javax.swing.JTextField correos;
    private javax.swing.JLabel exito;
    private javax.swing.JTextField fecha;
    private javax.swing.JFormattedTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mostrar;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registro;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
